version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
    environment:
      - ENVIRONMENT=development
      - TOKENIZERS_PARALLELISM=false
      - OMP_NUM_THREADS=1
    # Healthcheck adapté pour BLIP
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 300s  # 5 minutes pour permettre le chargement des modèles BLIP
    restart: unless-stopped
    # Limite de mémoire pour éviter les problèmes avec les modèles IA
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  uploads: