services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
    environment:
      - ENVIRONMENT=development
    # Ajouter un healthcheck pour s'assurer que le backend est bien démarré
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s  # Période initiale étendue pour permettre l'installation des dépendances
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy  # Attendre que le backend soit opérationnel
    restart: unless-stopped

volumes:
  uploads: