version: '3.8'

services:
  # Service API FastAPI
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/photosecours
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  # Service Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - './frontend:/app'
      - '/app/node_modules'

  # Base de données MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # File d'attente RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongodb_data: